{
    'name': 'پایه تلگرام',
    'version': '18.0.1.0.0',
    'category': 'Social',
    'summary': 'ماژول پایه برای ارتباط با تلگرام',
    'sequence': 1,
    'author': 'Amir Hosein Oskouei',
    'website': 'https://liinx.ir',
    'depends': ['base', 'mail'],
    'data': [
        'security/telegram_security.xml',
        'security/ir.model.access.csv',
        'data/ir_cron_data.xml',
        'views/telegram_bot_views.xml',
        'data/ir_sequence_data.xml',
        'views/telegram_log_views.xml',
        'views/telegram_info_views.xml',
        'views/res_partner_views.xml',
        'views/telegram_settings_views.xml',
        'views/telegram_editor_views.xml',
        'views/telegram_campaign_views.xml',
        'views/telegram_step_views.xml',
        'views/telegram_step_option_views.xml',
        'views/telegram_message_history_views.xml',
        'views/telegram_scheduled_message_views.xml',
        'views/telegram_menu.xml',
    ],
    'external_dependencies': {
        'python': ['aiohttp', 'cryptography', 'redis'],
    },
    'images': ['static/description/banner.png'],
    'application': True,
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
    'demo': [],
    'pre_init_hook': 'hooks.pre_init_hook',
    'post_init_hook': 'hooks.post_init_hook',
    'uninstall_hook': 'hooks.uninstall_hook',
}
