from . import telegram_bot
from . import telegram_info
from . import telegram_log
from . import send_message
from . import res_partner
from . import res_config_settings
from . import telegram_editor
from . import telegram_campaign
from . import telegram_step_option
from . import telegram_payment
from . import telegram_step
from . import telegram_message_delete
from . import telegram_step_handlers
from . import telegram_campaign_participant
from . import telegram_message_history
from . import telegram_scheduled_message
